# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "900a68f997eada9ee16dc16165389eef"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "BIMS Sync"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_orders,read_products,write_inventory,write_orders,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true
