"""initial schema

Revision ID: 6376be5c801c
Revises: 
Create Date: 2026-08-29 03:31:02.347890

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6376be5c801c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source', 'external_id')
    )
    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sync_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('product_hashes', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_summary', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_states_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('bims_base_url', sa.String(length=255), nullable=False),
    sa.Column('bims_api_key_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('shopify_shop_domain', sa.String(length=255), nullable=False),
    sa.Column('shopify_access_token_encrypted', sa.String(length=1024), nullable=False),
    sa.Column('shopify_webhook_secret', sa.String(length=255), nullable=False),
    sa.Column('shopify_location_id', sa.String(length=120), nullable=False),
    sa.Column('bims_posale_id', sa.Integer(), nullable=False),
    sa.Column('bims_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('bims_company_id', sa.Integer(), nullable=False),
    sa.Column('bims_currency_id', sa.Integer(), nullable=False),
    sa.Column('bims_payment_method_id', sa.Integer(), nullable=False),
    sa.Column('default_customer_contact_id', sa.Integer(), nullable=False),
    sa.Column('reorder_threshold', sa.Float(), nullable=False),
    sa.Column('reorder_strategy', sa.String(length=40), nullable=False),
    sa.Column('payment_provider', sa.String(length=40), nullable=True),
    sa.Column('provider_config', sa.JSON(), nullable=False),
    sa.Column('field_mappings', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))

    op.drop_table('tenants')
    with op.batch_alter_table('sync_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_states_tenant_id'))

    op.drop_table('sync_states')
    with op.batch_alter_table('processed_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_events_tenant_id'))

    op.drop_table('processed_events')
    # ### end Alembic commands ###
