"""Repository ports for persisted aggregates: tenants and sync state."""
from __future__ import annotations

from datetime import datetime
from typing import Protocol

from bims_shopify.domain.tenant import Tenant


class TenantRepository(Protocol):
    async def get_by_slug(self, slug: str) -> Tenant | None: ...

    async def get_by_shopify_domain(self, shopify_shop_domain: str) -> Tenant | None: ...

    async def get_by_id(self, tenant_id: int) -> Tenant | None: ...

    async def list_active(self) -> list[Tenant]: ...

    async def list_all(self) -> list[Tenant]: ...

    async def create(self, tenant: Tenant) -> Tenant: ...

    async def update(self, tenant: Tenant) -> Tenant: ...

    async def delete(self, tenant_id: int) -> None: ...


class SyncStateRepository(Protocol):
    async def get_last_run(self, tenant_id: int) -> datetime | None: ...

    async def set_last_run(self, tenant_id: int, when: datetime) -> None: ...

    async def get_product_hashes(self, tenant_id: int) -> dict[str, str]: ...

    async def set_product_hashes(self, tenant_id: int, hashes: dict[str, str]) -> None: ...

    async def has_processed_event(
        self, tenant_id: int, source: str, external_id: str
    ) -> bool: ...

    async def get_event_status(self, tenant_id: int, source: str, external_id: str) -> str | None: ...

    async def record_processed_event(
        self, tenant_id: int, source: str, external_id: str, payload_hash: str, status: str
    ) -> None: ...

    async def try_claim_event(
        self, tenant_id: int, source: str, external_id: str, payload_hash: str
    ) -> bool: ...

    async def mark_event_status(
        self, tenant_id: int, source: str, external_id: str, status: str
    ) -> None: ...

    async def delete_event(self, tenant_id: int, source: str, external_id: str) -> None: ...
